name: Build and push wal-g-exporter image

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  build-exporter-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/athomas22/wal-g-exporter # CHANGE TO YOUR DOCKER HUB REPO
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Debug tags
        run: echo "${{ steps.meta.outputs.tags }}"   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Set this secret in your GitHub repo settings
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # Set this secret in your GitHub repo settings

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
